var namespaceorg_1_1jabref_1_1gui_1_1commonfxcontrols =
[
    [ "CitationKeyPatternPanel", "classorg_1_1jabref_1_1gui_1_1commonfxcontrols_1_1_citation_key_pattern_panel.html", "classorg_1_1jabref_1_1gui_1_1commonfxcontrols_1_1_citation_key_pattern_panel" ],
    [ "CitationKeyPatternPanelItemModel", "classorg_1_1jabref_1_1gui_1_1commonfxcontrols_1_1_citation_key_pattern_panel_item_model.html", "classorg_1_1jabref_1_1gui_1_1commonfxcontrols_1_1_citation_key_pattern_panel_item_model" ],
    [ "CitationKeyPatternPanelViewModel", "classorg_1_1jabref_1_1gui_1_1commonfxcontrols_1_1_citation_key_pattern_panel_view_model.html", "classorg_1_1jabref_1_1gui_1_1commonfxcontrols_1_1_citation_key_pattern_panel_view_model" ],
    [ "FieldFormatterCleanupsPanel", "classorg_1_1jabref_1_1gui_1_1commonfxcontrols_1_1_field_formatter_cleanups_panel.html", "classorg_1_1jabref_1_1gui_1_1commonfxcontrols_1_1_field_formatter_cleanups_panel" ],
    [ "FieldFormatterCleanupsPanelViewModel", "classorg_1_1jabref_1_1gui_1_1commonfxcontrols_1_1_field_formatter_cleanups_panel_view_model.html", "classorg_1_1jabref_1_1gui_1_1commonfxcontrols_1_1_field_formatter_cleanups_panel_view_model" ],
    [ "SaveOrderConfigPanel", "classorg_1_1jabref_1_1gui_1_1commonfxcontrols_1_1_save_order_config_panel.html", "classorg_1_1jabref_1_1gui_1_1commonfxcontrols_1_1_save_order_config_panel" ],
    [ "SaveOrderConfigPanelViewModel", "classorg_1_1jabref_1_1gui_1_1commonfxcontrols_1_1_save_order_config_panel_view_model.html", "classorg_1_1jabref_1_1gui_1_1commonfxcontrols_1_1_save_order_config_panel_view_model" ]
];