var namespaceorg_1_1jabref_1_1logic_1_1shared =
[
    [ "event", "namespaceorg_1_1jabref_1_1logic_1_1shared_1_1event.html", "namespaceorg_1_1jabref_1_1logic_1_1shared_1_1event" ],
    [ "exception", "namespaceorg_1_1jabref_1_1logic_1_1shared_1_1exception.html", "namespaceorg_1_1jabref_1_1logic_1_1shared_1_1exception" ],
    [ "listener", "namespaceorg_1_1jabref_1_1logic_1_1shared_1_1listener.html", "namespaceorg_1_1jabref_1_1logic_1_1shared_1_1listener" ],
    [ "prefs", "namespaceorg_1_1jabref_1_1logic_1_1shared_1_1prefs.html", "namespaceorg_1_1jabref_1_1logic_1_1shared_1_1prefs" ],
    [ "security", "namespaceorg_1_1jabref_1_1logic_1_1shared_1_1security.html", "namespaceorg_1_1jabref_1_1logic_1_1shared_1_1security" ],
    [ "DatabaseConnection", "interfaceorg_1_1jabref_1_1logic_1_1shared_1_1_database_connection.html", "interfaceorg_1_1jabref_1_1logic_1_1shared_1_1_database_connection" ],
    [ "DatabaseConnectionProperties", "interfaceorg_1_1jabref_1_1logic_1_1shared_1_1_database_connection_properties.html", "interfaceorg_1_1jabref_1_1logic_1_1shared_1_1_database_connection_properties" ],
    [ "DatabaseLocation", "enumorg_1_1jabref_1_1logic_1_1shared_1_1_database_location.html", "enumorg_1_1jabref_1_1logic_1_1shared_1_1_database_location" ],
    [ "DatabaseNotSupportedException", "classorg_1_1jabref_1_1logic_1_1shared_1_1_database_not_supported_exception.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1_database_not_supported_exception" ],
    [ "DatabaseSynchronizer", "interfaceorg_1_1jabref_1_1logic_1_1shared_1_1_database_synchronizer.html", "interfaceorg_1_1jabref_1_1logic_1_1shared_1_1_database_synchronizer" ],
    [ "DBMSConnection", "classorg_1_1jabref_1_1logic_1_1shared_1_1_d_b_m_s_connection.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1_d_b_m_s_connection" ],
    [ "DBMSConnectionProperties", "classorg_1_1jabref_1_1logic_1_1shared_1_1_d_b_m_s_connection_properties.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1_d_b_m_s_connection_properties" ],
    [ "DBMSConnectionPropertiesBuilder", "classorg_1_1jabref_1_1logic_1_1shared_1_1_d_b_m_s_connection_properties_builder.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1_d_b_m_s_connection_properties_builder" ],
    [ "DBMSConnectionTest", "classorg_1_1jabref_1_1logic_1_1shared_1_1_d_b_m_s_connection_test.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1_d_b_m_s_connection_test" ],
    [ "DBMSProcessor", "classorg_1_1jabref_1_1logic_1_1shared_1_1_d_b_m_s_processor.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1_d_b_m_s_processor" ],
    [ "DBMSSynchronizer", "classorg_1_1jabref_1_1logic_1_1shared_1_1_d_b_m_s_synchronizer.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1_d_b_m_s_synchronizer" ],
    [ "DBMSSynchronizerTest", "classorg_1_1jabref_1_1logic_1_1shared_1_1_d_b_m_s_synchronizer_test.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1_d_b_m_s_synchronizer_test" ],
    [ "DBMSType", "enumorg_1_1jabref_1_1logic_1_1shared_1_1_d_b_m_s_type.html", "enumorg_1_1jabref_1_1logic_1_1shared_1_1_d_b_m_s_type" ],
    [ "DBMSTypeTest", "classorg_1_1jabref_1_1logic_1_1shared_1_1_d_b_m_s_type_test.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1_d_b_m_s_type_test" ],
    [ "MySQLProcessor", "classorg_1_1jabref_1_1logic_1_1shared_1_1_my_s_q_l_processor.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1_my_s_q_l_processor" ],
    [ "OracleProcessor", "classorg_1_1jabref_1_1logic_1_1shared_1_1_oracle_processor.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1_oracle_processor" ],
    [ "PostgreSQLProcessor", "classorg_1_1jabref_1_1logic_1_1shared_1_1_postgre_s_q_l_processor.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1_postgre_s_q_l_processor" ],
    [ "SynchronizationTestEventListener", "classorg_1_1jabref_1_1logic_1_1shared_1_1_synchronization_test_event_listener.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1_synchronization_test_event_listener" ],
    [ "SynchronizationTestSimulator", "classorg_1_1jabref_1_1logic_1_1shared_1_1_synchronization_test_simulator.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1_synchronization_test_simulator" ],
    [ "TestConnector", "classorg_1_1jabref_1_1logic_1_1shared_1_1_test_connector.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1_test_connector" ],
    [ "TestManager", "classorg_1_1jabref_1_1logic_1_1shared_1_1_test_manager.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1_test_manager" ]
];