var namespaceorg_1_1jabref_1_1gui_1_1preferences =
[
    [ "AbstractPreferenceTabView", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_abstract_preference_tab_view.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_abstract_preference_tab_view" ],
    [ "AppearanceTabView", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_appearance_tab_view.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_appearance_tab_view" ],
    [ "AppearanceTabViewModel", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_appearance_tab_view_model.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_appearance_tab_view_model" ],
    [ "CitationKeyPatternTabView", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_citation_key_pattern_tab_view.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_citation_key_pattern_tab_view" ],
    [ "CitationKeyPatternTabViewModel", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_citation_key_pattern_tab_view_model.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_citation_key_pattern_tab_view_model" ],
    [ "EntryEditorTabView", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_entry_editor_tab_view.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_entry_editor_tab_view" ],
    [ "EntryEditorTabViewModel", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_entry_editor_tab_view_model.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_entry_editor_tab_view_model" ],
    [ "ExternalTabView", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_external_tab_view.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_external_tab_view" ],
    [ "ExternalTabViewModel", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_external_tab_view_model.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_external_tab_view_model" ],
    [ "FileTabView", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_file_tab_view.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_file_tab_view" ],
    [ "FileTabViewModel", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_file_tab_view_model.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_file_tab_view_model" ],
    [ "GeneralTabView", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_general_tab_view.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_general_tab_view" ],
    [ "GeneralTabViewModel", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_general_tab_view_model.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_general_tab_view_model" ],
    [ "GroupsTabView", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_groups_tab_view.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_groups_tab_view" ],
    [ "GroupsTabViewModel", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_groups_tab_view_model.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_groups_tab_view_model" ],
    [ "LinkedFilesTabView", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_linked_files_tab_view.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_linked_files_tab_view" ],
    [ "LinkedFilesTabViewModel", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_linked_files_tab_view_model.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_linked_files_tab_view_model" ],
    [ "NameFormatterItemModel", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_name_formatter_item_model.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_name_formatter_item_model" ],
    [ "NameFormatterTabView", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_name_formatter_tab_view.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_name_formatter_tab_view" ],
    [ "NameFormatterTabViewModel", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_name_formatter_tab_view_model.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_name_formatter_tab_view_model" ],
    [ "NetworkTabView", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_network_tab_view.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_network_tab_view" ],
    [ "NetworkTabViewModel", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_network_tab_view_model.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_network_tab_view_model" ],
    [ "PreferencesDialogView", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_preferences_dialog_view.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_preferences_dialog_view" ],
    [ "PreferencesDialogViewModel", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_preferences_dialog_view_model.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_preferences_dialog_view_model" ],
    [ "PreferencesFilterDialog", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_preferences_filter_dialog.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_preferences_filter_dialog" ],
    [ "PreferenceTabViewModel", "interfaceorg_1_1jabref_1_1gui_1_1preferences_1_1_preference_tab_view_model.html", "interfaceorg_1_1jabref_1_1gui_1_1preferences_1_1_preference_tab_view_model" ],
    [ "PreviewTabView", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_preview_tab_view.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_preview_tab_view" ],
    [ "PreviewTabViewModel", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_preview_tab_view_model.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_preview_tab_view_model" ],
    [ "ShowPreferencesAction", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_show_preferences_action.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_show_preferences_action" ],
    [ "TableTabView", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_table_tab_view.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_table_tab_view" ],
    [ "TableTabViewModel", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_table_tab_view_model.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_table_tab_view_model" ],
    [ "XmpPrivacyTabView", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_xmp_privacy_tab_view.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_xmp_privacy_tab_view" ],
    [ "XmpPrivacyTabViewModel", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_xmp_privacy_tab_view_model.html", "classorg_1_1jabref_1_1gui_1_1preferences_1_1_xmp_privacy_tab_view_model" ]
];