var searchData=
[
  ['abbreviateaction_9105',['AbbreviateAction',['../classorg_1_1jabref_1_1gui_1_1journals_1_1_abbreviate_action.html',1,'org::jabref::gui::journals']]],
  ['abbreviation_9106',['Abbreviation',['../classorg_1_1jabref_1_1logic_1_1journals_1_1_abbreviation.html',1,'org::jabref::logic::journals']]],
  ['abbreviationchecker_9107',['AbbreviationChecker',['../classorg_1_1jabref_1_1logic_1_1integrity_1_1_abbreviation_checker.html',1,'org::jabref::logic::integrity']]],
  ['abbreviationformat_9108',['AbbreviationFormat',['../classorg_1_1jabref_1_1logic_1_1journals_1_1_abbreviation_format.html',1,'org::jabref::logic::journals']]],
  ['abbreviationparser_9109',['AbbreviationParser',['../classorg_1_1jabref_1_1logic_1_1journals_1_1_abbreviation_parser.html',1,'org::jabref::logic::journals']]],
  ['abbreviationsfileviewmodel_9110',['AbbreviationsFileViewModel',['../classorg_1_1jabref_1_1gui_1_1journals_1_1_abbreviations_file_view_model.html',1,'org::jabref::gui::journals']]],
  ['abbreviationstyle_9111',['AbbreviationStyle',['../enumorg_1_1jabref_1_1gui_1_1maintable_1_1_main_table_name_format_preferences_1_1_abbreviation_style.html',1,'org::jabref::gui::maintable::MainTableNameFormatPreferences']]],
  ['abbreviationtype_9112',['AbbreviationType',['../enumorg_1_1jabref_1_1gui_1_1journals_1_1_abbreviation_type.html',1,'org::jabref::gui::journals']]],
  ['abbreviationviewmodel_9113',['AbbreviationViewModel',['../classorg_1_1jabref_1_1gui_1_1journals_1_1_abbreviation_view_model.html',1,'org::jabref::gui::journals']]],
  ['abbreviationwriter_9114',['AbbreviationWriter',['../classorg_1_1jabref_1_1logic_1_1journals_1_1_abbreviation_writer.html',1,'org::jabref::logic::journals']]],
  ['aboutaction_9115',['AboutAction',['../classorg_1_1jabref_1_1gui_1_1help_1_1_about_action.html',1,'org::jabref::gui::help']]],
  ['aboutdialogview_9116',['AboutDialogView',['../classorg_1_1jabref_1_1gui_1_1help_1_1_about_dialog_view.html',1,'org::jabref::gui::help']]],
  ['aboutdialogviewmodel_9117',['AboutDialogViewModel',['../classorg_1_1jabref_1_1gui_1_1help_1_1_about_dialog_view_model.html',1,'org::jabref::gui::help']]],
  ['abstractcitationkeypattern_9118',['AbstractCitationKeyPattern',['../classorg_1_1jabref_1_1logic_1_1citationkeypattern_1_1_abstract_citation_key_pattern.html',1,'org::jabref::logic::citationkeypattern']]],
  ['abstracteditorviewmodel_9119',['AbstractEditorViewModel',['../classorg_1_1jabref_1_1gui_1_1fieldeditors_1_1_abstract_editor_view_model.html',1,'org::jabref::gui::fieldeditors']]],
  ['abstractgroup_9120',['AbstractGroup',['../classorg_1_1jabref_1_1model_1_1groups_1_1_abstract_group.html',1,'org::jabref::model::groups']]],
  ['abstractisbnfetcher_9121',['AbstractIsbnFetcher',['../classorg_1_1jabref_1_1logic_1_1importer_1_1fetcher_1_1_abstract_isbn_fetcher.html',1,'org::jabref::logic::importer::fetcher']]],
  ['abstractparamlayoutformatter_9122',['AbstractParamLayoutFormatter',['../classorg_1_1jabref_1_1logic_1_1layout_1_1_abstract_param_layout_formatter.html',1,'org::jabref::logic::layout']]],
  ['abstractpreferencetabview_9123',['AbstractPreferenceTabView',['../classorg_1_1jabref_1_1gui_1_1preferences_1_1_abstract_preference_tab_view.html',1,'org::jabref::gui::preferences']]],
  ['abstractpreferencetabview_3c_20appearancetabviewmodel_20_3e_9124',['AbstractPreferenceTabView&lt; AppearanceTabViewModel &gt;',['../classorg_1_1jabref_1_1gui_1_1preferences_1_1_abstract_preference_tab_view.html',1,'org::jabref::gui::preferences']]],
  ['abstractpreferencetabview_3c_20citationkeypatterntabviewmodel_20_3e_9125',['AbstractPreferenceTabView&lt; CitationKeyPatternTabViewModel &gt;',['../classorg_1_1jabref_1_1gui_1_1preferences_1_1_abstract_preference_tab_view.html',1,'org::jabref::gui::preferences']]],
  ['abstractpreferencetabview_3c_20entryeditortabviewmodel_20_3e_9126',['AbstractPreferenceTabView&lt; EntryEditorTabViewModel &gt;',['../classorg_1_1jabref_1_1gui_1_1preferences_1_1_abstract_preference_tab_view.html',1,'org::jabref::gui::preferences']]],
  ['abstractpreferencetabview_3c_20externaltabviewmodel_20_3e_9127',['AbstractPreferenceTabView&lt; ExternalTabViewModel &gt;',['../classorg_1_1jabref_1_1gui_1_1preferences_1_1_abstract_preference_tab_view.html',1,'org::jabref::gui::preferences']]],
  ['abstractpreferencetabview_3c_20filetabviewmodel_20_3e_9128',['AbstractPreferenceTabView&lt; FileTabViewModel &gt;',['../classorg_1_1jabref_1_1gui_1_1preferences_1_1_abstract_preference_tab_view.html',1,'org::jabref::gui::preferences']]],
  ['abstractpreferencetabview_3c_20generaltabviewmodel_20_3e_9129',['AbstractPreferenceTabView&lt; GeneralTabViewModel &gt;',['../classorg_1_1jabref_1_1gui_1_1preferences_1_1_abstract_preference_tab_view.html',1,'org::jabref::gui::preferences']]],
  ['abstractpreferencetabview_3c_20groupstabviewmodel_20_3e_9130',['AbstractPreferenceTabView&lt; GroupsTabViewModel &gt;',['../classorg_1_1jabref_1_1gui_1_1preferences_1_1_abstract_preference_tab_view.html',1,'org::jabref::gui::preferences']]],
  ['abstractpreferencetabview_3c_20linkedfilestabviewmodel_20_3e_9131',['AbstractPreferenceTabView&lt; LinkedFilesTabViewModel &gt;',['../classorg_1_1jabref_1_1gui_1_1preferences_1_1_abstract_preference_tab_view.html',1,'org::jabref::gui::preferences']]],
  ['abstractpreferencetabview_3c_20nameformattertabviewmodel_20_3e_9132',['AbstractPreferenceTabView&lt; NameFormatterTabViewModel &gt;',['../classorg_1_1jabref_1_1gui_1_1preferences_1_1_abstract_preference_tab_view.html',1,'org::jabref::gui::preferences']]],
  ['abstractpreferencetabview_3c_20networktabviewmodel_20_3e_9133',['AbstractPreferenceTabView&lt; NetworkTabViewModel &gt;',['../classorg_1_1jabref_1_1gui_1_1preferences_1_1_abstract_preference_tab_view.html',1,'org::jabref::gui::preferences']]],
  ['abstractpreferencetabview_3c_20previewtabviewmodel_20_3e_9134',['AbstractPreferenceTabView&lt; PreviewTabViewModel &gt;',['../classorg_1_1jabref_1_1gui_1_1preferences_1_1_abstract_preference_tab_view.html',1,'org::jabref::gui::preferences']]],
  ['abstractpreferencetabview_3c_20tabletabviewmodel_20_3e_9135',['AbstractPreferenceTabView&lt; TableTabViewModel &gt;',['../classorg_1_1jabref_1_1gui_1_1preferences_1_1_abstract_preference_tab_view.html',1,'org::jabref::gui::preferences']]],
  ['abstractpreferencetabview_3c_20xmpprivacytabviewmodel_20_3e_9136',['AbstractPreferenceTabView&lt; XmpPrivacyTabViewModel &gt;',['../classorg_1_1jabref_1_1gui_1_1preferences_1_1_abstract_preference_tab_view.html',1,'org::jabref::gui::preferences']]],
  ['abstractpushtoapplication_9137',['AbstractPushToApplication',['../classorg_1_1jabref_1_1gui_1_1push_1_1_abstract_push_to_application.html',1,'org::jabref::gui::push']]],
  ['abstractundoablejabrefedit_9138',['AbstractUndoableJabRefEdit',['../classorg_1_1jabref_1_1gui_1_1undo_1_1_abstract_undoable_jab_ref_edit.html',1,'org::jabref::gui::undo']]],
  ['abstractviewmodel_9139',['AbstractViewModel',['../classorg_1_1jabref_1_1gui_1_1_abstract_view_model.html',1,'org::jabref::gui']]],
  ['acmportalfetcher_9140',['ACMPortalFetcher',['../classorg_1_1jabref_1_1logic_1_1importer_1_1fetcher_1_1_a_c_m_portal_fetcher.html',1,'org::jabref::logic::importer::fetcher']]],
  ['acs_9141',['ACS',['../classorg_1_1jabref_1_1logic_1_1importer_1_1fetcher_1_1_a_c_s.html',1,'org::jabref::logic::importer::fetcher']]],
  ['action_9142',['Action',['../interfaceorg_1_1jabref_1_1gui_1_1actions_1_1_action.html',1,'org::jabref::gui::actions']]],
  ['actionfactory_9143',['ActionFactory',['../classorg_1_1jabref_1_1gui_1_1actions_1_1_action_factory.html',1,'org::jabref::gui::actions']]],
  ['actionhelper_9144',['ActionHelper',['../classorg_1_1jabref_1_1gui_1_1actions_1_1_action_helper.html',1,'org::jabref::gui::actions']]],
  ['addbracesformatter_9145',['AddBracesFormatter',['../classorg_1_1jabref_1_1logic_1_1formatter_1_1bibtexfields_1_1_add_braces_formatter.html',1,'org::jabref::logic::formatter::bibtexfields']]],
  ['addundoableactionevent_9146',['AddUndoableActionEvent',['../classorg_1_1jabref_1_1logic_1_1undo_1_1_add_undoable_action_event.html',1,'org::jabref::logic::undo']]],
  ['advancedcitedialogview_9147',['AdvancedCiteDialogView',['../classorg_1_1jabref_1_1gui_1_1openoffice_1_1_advanced_cite_dialog_view.html',1,'org::jabref::gui::openoffice']]],
  ['advancedcitedialogviewmodel_9148',['AdvancedCiteDialogViewModel',['../classorg_1_1jabref_1_1gui_1_1openoffice_1_1_advanced_cite_dialog_view_model.html',1,'org::jabref::gui::openoffice']]],
  ['allentriesgroup_9149',['AllEntriesGroup',['../classorg_1_1jabref_1_1model_1_1groups_1_1_all_entries_group.html',1,'org::jabref::model::groups']]],
  ['allowedtouseawt_9150',['AllowedToUseAwt',['../interfaceorg_1_1jabref_1_1architecture_1_1_allowed_to_use_awt.html',1,'org::jabref::architecture']]],
  ['allowedtouselogic_9151',['AllowedToUseLogic',['../interfaceorg_1_1jabref_1_1architecture_1_1_allowed_to_use_logic.html',1,'org::jabref::architecture']]],
  ['andmatcher_9152',['AndMatcher',['../classorg_1_1jabref_1_1model_1_1search_1_1matchers_1_1_and_matcher.html',1,'org::jabref::model::search::matchers']]],
  ['annotationimporter_9153',['AnnotationImporter',['../interfaceorg_1_1jabref_1_1logic_1_1pdf_1_1_annotation_importer.html',1,'org::jabref::logic::pdf']]],
  ['apachecommonslang3allowed_9154',['ApacheCommonsLang3Allowed',['../interfaceorg_1_1jabref_1_1architecture_1_1_apache_commons_lang3_allowed.html',1,'org::jabref::architecture']]],
  ['appearancepreferences_9155',['AppearancePreferences',['../classorg_1_1jabref_1_1preferences_1_1_appearance_preferences.html',1,'org::jabref::preferences']]],
  ['appearancetabview_9156',['AppearanceTabView',['../classorg_1_1jabref_1_1gui_1_1preferences_1_1_appearance_tab_view.html',1,'org::jabref::gui::preferences']]],
  ['appearancetabviewmodel_9157',['AppearanceTabViewModel',['../classorg_1_1jabref_1_1gui_1_1preferences_1_1_appearance_tab_view_model.html',1,'org::jabref::gui::preferences']]],
  ['appendpersonnamesstrategy_9158',['AppendPersonNamesStrategy',['../classorg_1_1jabref_1_1gui_1_1autocompleter_1_1_append_person_names_strategy.html',1,'org::jabref::gui::autocompleter']]],
  ['appendwordsstrategy_9159',['AppendWordsStrategy',['../classorg_1_1jabref_1_1gui_1_1autocompleter_1_1_append_words_strategy.html',1,'org::jabref::gui::autocompleter']]],
  ['applicationinsightsappender_9160',['ApplicationInsightsAppender',['../classorg_1_1jabref_1_1gui_1_1logging_1_1_application_insights_appender.html',1,'org::jabref::gui::logging']]],
  ['applicationinsightslogevent_9161',['ApplicationInsightsLogEvent',['../classorg_1_1jabref_1_1gui_1_1logging_1_1_application_insights_log_event.html',1,'org::jabref::gui::logging']]],
  ['apsfetcher_9162',['ApsFetcher',['../classorg_1_1jabref_1_1logic_1_1importer_1_1fetcher_1_1_aps_fetcher.html',1,'org::jabref::logic::importer::fetcher']]],
  ['argumentprocessor_9163',['ArgumentProcessor',['../classorg_1_1jabref_1_1cli_1_1_argument_processor.html',1,'org::jabref::cli']]],
  ['arxiv_9164',['ArXiv',['../classorg_1_1jabref_1_1logic_1_1importer_1_1fetcher_1_1_ar_xiv.html',1,'org::jabref::logic::importer::fetcher']]],
  ['arxiventry_9165',['ArXivEntry',['../classorg_1_1jabref_1_1logic_1_1importer_1_1fetcher_1_1_ar_xiv_1_1_ar_xiv_entry.html',1,'org::jabref::logic::importer::fetcher::ArXiv']]],
  ['arxividentifier_9166',['ArXivIdentifier',['../classorg_1_1jabref_1_1model_1_1entry_1_1identifier_1_1_ar_xiv_identifier.html',1,'org::jabref::model::entry::identifier']]],
  ['asciicharacterchecker_9167',['ASCIICharacterChecker',['../classorg_1_1jabref_1_1logic_1_1integrity_1_1_a_s_c_i_i_character_checker.html',1,'org::jabref::logic::integrity']]],
  ['astrophysicsdatasystem_9168',['AstrophysicsDataSystem',['../classorg_1_1jabref_1_1logic_1_1importer_1_1fetcher_1_1_astrophysics_data_system.html',1,'org::jabref::logic::importer::fetcher']]],
  ['atomicfileoutputstream_9169',['AtomicFileOutputStream',['../classorg_1_1jabref_1_1logic_1_1exporter_1_1_atomic_file_output_stream.html',1,'org::jabref::logic::exporter']]],
  ['atomicfilewriter_9170',['AtomicFileWriter',['../classorg_1_1jabref_1_1logic_1_1exporter_1_1_atomic_file_writer.html',1,'org::jabref::logic::exporter']]],
  ['attachfileaction_9171',['AttachFileAction',['../classorg_1_1jabref_1_1gui_1_1filelist_1_1_attach_file_action.html',1,'org::jabref::gui::filelist']]],
  ['author_9172',['Author',['../classorg_1_1jabref_1_1model_1_1entry_1_1_author.html',1,'org::jabref::model::entry']]],
  ['authorabbreviator_9173',['AuthorAbbreviator',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_abbreviator.html',1,'org::jabref::logic::layout::format']]],
  ['authorandscommareplacer_9174',['AuthorAndsCommaReplacer',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_ands_comma_replacer.html',1,'org::jabref::logic::layout::format']]],
  ['authorandsreplacer_9175',['AuthorAndsReplacer',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_ands_replacer.html',1,'org::jabref::logic::layout::format']]],
  ['authorandtosemicolonreplacer_9176',['AuthorAndToSemicolonReplacer',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_and_to_semicolon_replacer.html',1,'org::jabref::logic::layout::format']]],
  ['authorfirstabbrlastcommas_9177',['AuthorFirstAbbrLastCommas',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_first_abbr_last_commas.html',1,'org::jabref::logic::layout::format']]],
  ['authorfirstabbrlastoxfordcommas_9178',['AuthorFirstAbbrLastOxfordCommas',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_first_abbr_last_oxford_commas.html',1,'org::jabref::logic::layout::format']]],
  ['authorfirstfirst_9179',['AuthorFirstFirst',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_first_first.html',1,'org::jabref::logic::layout::format']]],
  ['authorfirstfirstcommas_9180',['AuthorFirstFirstCommas',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_first_first_commas.html',1,'org::jabref::logic::layout::format']]],
  ['authorfirstlastcommas_9181',['AuthorFirstLastCommas',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_first_last_commas.html',1,'org::jabref::logic::layout::format']]],
  ['authorfirstlastoxfordcommas_9182',['AuthorFirstLastOxfordCommas',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_first_last_oxford_commas.html',1,'org::jabref::logic::layout::format']]],
  ['authorlastfirst_9183',['AuthorLastFirst',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_last_first.html',1,'org::jabref::logic::layout::format']]],
  ['authorlastfirstabbrcommas_9184',['AuthorLastFirstAbbrCommas',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_last_first_abbr_commas.html',1,'org::jabref::logic::layout::format']]],
  ['authorlastfirstabbreviator_9185',['AuthorLastFirstAbbreviator',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_last_first_abbreviator.html',1,'org::jabref::logic::layout::format']]],
  ['authorlastfirstabbroxfordcommas_9186',['AuthorLastFirstAbbrOxfordCommas',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_last_first_abbr_oxford_commas.html',1,'org::jabref::logic::layout::format']]],
  ['authorlastfirstcommas_9187',['AuthorLastFirstCommas',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_last_first_commas.html',1,'org::jabref::logic::layout::format']]],
  ['authorlastfirstoxfordcommas_9188',['AuthorLastFirstOxfordCommas',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_last_first_oxford_commas.html',1,'org::jabref::logic::layout::format']]],
  ['authorlf_5fff_9189',['AuthorLF_FF',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_l_f___f_f.html',1,'org::jabref::logic::layout::format']]],
  ['authorlf_5fffabbr_9190',['AuthorLF_FFAbbr',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_l_f___f_f_abbr.html',1,'org::jabref::logic::layout::format']]],
  ['authorlist_9191',['AuthorList',['../classorg_1_1jabref_1_1model_1_1entry_1_1_author_list.html',1,'org::jabref::model::entry']]],
  ['authorlistparser_9192',['AuthorListParser',['../classorg_1_1jabref_1_1logic_1_1importer_1_1_author_list_parser.html',1,'org::jabref::logic::importer']]],
  ['authornatbib_9193',['AuthorNatBib',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_nat_bib.html',1,'org::jabref::logic::layout::format']]],
  ['authororgsci_9194',['AuthorOrgSci',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_author_org_sci.html',1,'org::jabref::logic::layout::format']]],
  ['authors_9195',['Authors',['../classorg_1_1jabref_1_1logic_1_1layout_1_1format_1_1_authors.html',1,'org::jabref::logic::layout::format']]],
  ['autocompletefirstnamemode_9196',['AutoCompleteFirstNameMode',['../enumorg_1_1jabref_1_1gui_1_1autocompleter_1_1_auto_complete_first_name_mode.html',1,'org::jabref::gui::autocompleter']]],
  ['autocompletepreferences_9197',['AutoCompletePreferences',['../classorg_1_1jabref_1_1gui_1_1autocompleter_1_1_auto_complete_preferences.html',1,'org::jabref::gui::autocompleter']]],
  ['autocompletioninput_9198',['AutoCompletionInput',['../classorg_1_1jabref_1_1gui_1_1autocompleter_1_1_auto_completion_input.html',1,'org::jabref::gui::autocompleter']]],
  ['autocompletionstrategy_9199',['AutoCompletionStrategy',['../interfaceorg_1_1jabref_1_1gui_1_1autocompleter_1_1_auto_completion_strategy.html',1,'org::jabref::gui::autocompleter']]],
  ['autocompletiontextinputbinding_9200',['AutoCompletionTextInputBinding',['../classorg_1_1jabref_1_1gui_1_1autocompleter_1_1_auto_completion_text_input_binding.html',1,'org::jabref::gui::autocompleter']]],
  ['autolinkfilesaction_9201',['AutoLinkFilesAction',['../classorg_1_1jabref_1_1gui_1_1externalfiles_1_1_auto_link_files_action.html',1,'org::jabref::gui::externalfiles']]],
  ['autolinkpreferences_9202',['AutoLinkPreferences',['../classorg_1_1jabref_1_1logic_1_1util_1_1io_1_1_auto_link_preferences.html',1,'org::jabref::logic::util::io']]],
  ['automaticgroup_9203',['AutomaticGroup',['../classorg_1_1jabref_1_1model_1_1groups_1_1_automatic_group.html',1,'org::jabref::model::groups']]],
  ['automatickeywordgroup_9204',['AutomaticKeywordGroup',['../classorg_1_1jabref_1_1model_1_1groups_1_1_automatic_keyword_group.html',1,'org::jabref::model::groups']]],
  ['automaticpersonsgroup_9205',['AutomaticPersonsGroup',['../classorg_1_1jabref_1_1model_1_1groups_1_1_automatic_persons_group.html',1,'org::jabref::model::groups']]],
  ['autosaveevent_9206',['AutosaveEvent',['../classorg_1_1jabref_1_1model_1_1database_1_1event_1_1_autosave_event.html',1,'org::jabref::model::database::event']]],
  ['autosavemanager_9207',['AutosaveManager',['../classorg_1_1jabref_1_1logic_1_1autosaveandbackup_1_1_autosave_manager.html',1,'org::jabref::logic::autosaveandbackup']]],
  ['autosaveuimanager_9208',['AutosaveUiManager',['../classorg_1_1jabref_1_1gui_1_1dialogs_1_1_autosave_ui_manager.html',1,'org::jabref::gui::dialogs']]],
  ['autosetfilelinksutil_9209',['AutoSetFileLinksUtil',['../classorg_1_1jabref_1_1gui_1_1externalfiles_1_1_auto_set_file_links_util.html',1,'org::jabref::gui::externalfiles']]],
  ['auxcommandline_9210',['AuxCommandLine',['../classorg_1_1jabref_1_1cli_1_1_aux_command_line.html',1,'org::jabref::cli']]],
  ['auxparser_9211',['AuxParser',['../interfaceorg_1_1jabref_1_1logic_1_1auxparser_1_1_aux_parser.html',1,'org::jabref::logic::auxparser']]],
  ['auxparserresult_9212',['AuxParserResult',['../classorg_1_1jabref_1_1logic_1_1auxparser_1_1_aux_parser_result.html',1,'org::jabref::logic::auxparser']]],
  ['auxparserresultviewmodel_9213',['AuxParserResultViewModel',['../classorg_1_1jabref_1_1gui_1_1auximport_1_1_aux_parser_result_view_model.html',1,'org::jabref::gui::auximport']]]
];
