var namespaceorg_1_1jabref_1_1logic_1_1shared_1_1exception =
[
    [ "InvalidDBMSConnectionPropertiesException", "classorg_1_1jabref_1_1logic_1_1shared_1_1exception_1_1_invalid_d_b_m_s_connection_properties_exception.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1exception_1_1_invalid_d_b_m_s_connection_properties_exception" ],
    [ "NotASharedDatabaseException", "classorg_1_1jabref_1_1logic_1_1shared_1_1exception_1_1_not_a_shared_database_exception.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1exception_1_1_not_a_shared_database_exception" ],
    [ "OfflineLockException", "classorg_1_1jabref_1_1logic_1_1shared_1_1exception_1_1_offline_lock_exception.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1exception_1_1_offline_lock_exception" ],
    [ "SharedEntryNotPresentException", "classorg_1_1jabref_1_1logic_1_1shared_1_1exception_1_1_shared_entry_not_present_exception.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1exception_1_1_shared_entry_not_present_exception" ]
];