var namespaceorg_1_1jabref_1_1logic_1_1shared_1_1listener =
[
    [ "OracleNotificationListener", "classorg_1_1jabref_1_1logic_1_1shared_1_1listener_1_1_oracle_notification_listener.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1listener_1_1_oracle_notification_listener" ],
    [ "PostgresSQLNotificationListener", "classorg_1_1jabref_1_1logic_1_1shared_1_1listener_1_1_postgres_s_q_l_notification_listener.html", "classorg_1_1jabref_1_1logic_1_1shared_1_1listener_1_1_postgres_s_q_l_notification_listener" ]
];