var namespaceorg_1_1jabref_1_1gui_1_1libraryproperties =
[
    [ "LibraryPropertiesAction", "classorg_1_1jabref_1_1gui_1_1libraryproperties_1_1_library_properties_action.html", "classorg_1_1jabref_1_1gui_1_1libraryproperties_1_1_library_properties_action" ],
    [ "LibraryPropertiesDialogView", "classorg_1_1jabref_1_1gui_1_1libraryproperties_1_1_library_properties_dialog_view.html", "classorg_1_1jabref_1_1gui_1_1libraryproperties_1_1_library_properties_dialog_view" ],
    [ "LibraryPropertiesDialogViewModel", "classorg_1_1jabref_1_1gui_1_1libraryproperties_1_1_library_properties_dialog_view_model.html", "classorg_1_1jabref_1_1gui_1_1libraryproperties_1_1_library_properties_dialog_view_model" ]
];