name: Doxygen and deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - doxygen
      - seb

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Doxygen
        uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: '.'
          doxyfile-path: './Doxyfile'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html