name: SonarQube Analysis
on:
  push:
    branches:
      - master
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
        projectKey: "dat265group2"
        projectName: "Software-Evolution-Group-2"
        projectVersion: "v0.0.1"
